### CREATE HOUSE (ADMIN)
POST http://localhost:8080/house/create
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2NzI0MTg4MTMsImVtYWlsIjoiYWRtaW5jZWVrQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNjcyNTA1MjEzLCJpc3MiOiJob3VzZWZveCB0ZXN0IHBvcnRhbGkifQ.7-OT9X4tRDszZZLXaYHuQkGNset_uMRXVRRQNO9hafcXVUXK7ml5gTsOqCvyrBmYe5QqQSaDlW3JealV-9Zcyg
Content-Type: application/json

{
  "title": "Oq uy",
  "description": "Bu uy faqat boylar uchun",
  "location": "Washington",
  "type": "DACHA",
  "price": 1000,
  "rooms": 15,
  "phone": "+998339561608"
}

### UPDATE HOUSE (ADMIN)
PUT http://localhost:8080/house/update/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2NzIyNTQwNTcsImVtYWlsIjoiYWRtaW5jZWVrQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNjcyMzQwNDU3LCJpc3MiOiJob3VzZWZveCB0ZXN0IHBvcnRhbGkifQ.-L80wiX9sRkUPJJDcyokzOGfSj3PEoQ1w81SFMETRDOfq9p4II0oeqDAD3XsV0retOi3BlAcNiRDhHezcbmXCA
Content-Type: application/json

{
  "title": "Qora uy",
  "description": "Bu sening ota onangni uyi",
  "location": "Tug'ilgan joying",
  "type": "YER",
  "price": 1,
  "rooms": 1000,
  "phone": "+998339561608"
}

### DELETE HOUSE (ADMIN)
DELETE http://localhost:8080/house/delete/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2NzIyNTQwNTcsImVtYWlsIjoiYWRtaW5jZWVrQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNjcyMzQwNDU3LCJpc3MiOiJob3VzZWZveCB0ZXN0IHBvcnRhbGkifQ.-L80wiX9sRkUPJJDcyokzOGfSj3PEoQ1w81SFMETRDOfq9p4II0oeqDAD3XsV0retOi3BlAcNiRDhHezcbmXCA

### GET HOUSE (USER)
GET http://localhost:8080/house/get/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2NzIyNTcxNjEsImVtYWlsIjoibmF6YXJvdmF6aW1qb244ODhAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTY3MjM0MzU2MSwiaXNzIjoiaG91c2Vmb3ggdGVzdCBwb3J0YWxpIn0.qjNjZ5lQI9wKqqTrHGR9Afh1kkCod3e7qkdSbQIZw6vLP__adhbV5Pt_VCxcYL2qWMjaa5_0MSvDsKd7L3TOQw

### GET ALL HOUSES PAGINATION (USER, ADMIN)
GET http://localhost:8080/house/get/all?page=0&size=1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2NzIyNTcxNjEsImVtYWlsIjoibmF6YXJvdmF6aW1qb244ODhAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTY3MjM0MzU2MSwiaXNzIjoiaG91c2Vmb3ggdGVzdCBwb3J0YWxpIn0.qjNjZ5lQI9wKqqTrHGR9Afh1kkCod3e7qkdSbQIZw6vLP__adhbV5Pt_VCxcYL2qWMjaa5_0MSvDsKd7L3TOQw

### GET TOP 10 LIKED HOUSES (ADMIN)
GET http://localhost:8080/house/get/top/liked
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2NzIyNTQwNTcsImVtYWlsIjoiYWRtaW5jZWVrQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNjcyMzQwNDU3LCJpc3MiOiJob3VzZWZveCB0ZXN0IHBvcnRhbGkifQ.-L80wiX9sRkUPJJDcyokzOGfSj3PEoQ1w81SFMETRDOfq9p4II0oeqDAD3XsV0retOi3BlAcNiRDhHezcbmXCA

### GET TOP 10 VIEWED HOUSES (ADMIN)
GET http://localhost:8080/house/get/top/viewed
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2NzIyNTQwNTcsImVtYWlsIjoiYWRtaW5jZWVrQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNjcyMzQwNDU3LCJpc3MiOiJob3VzZWZveCB0ZXN0IHBvcnRhbGkifQ.-L80wiX9sRkUPJJDcyokzOGfSj3PEoQ1w81SFMETRDOfq9p4II0oeqDAD3XsV0retOi3BlAcNiRDhHezcbmXCA
